apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdhpai221-6-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/rhdhpai221-6/overlays/tekton
    repoURL: https://github.com/rhdh-JslYoon-org/rhdhpai221-6-gitops.git
    targetRevision: main
  destination:
    namespace: rhdhpai221-6
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
