apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rhdhpai221-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdhpai221-6
  name: rhdhpai221-6
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
