kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhdhpai221-6-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rhdhpai221-6-dsp-job
    namespace: rhdhpai221-6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhdhpai221-6-dsp-job-role
