apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai221-6
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai221-6:d7db753dccce5daf94f9764aaee89689d860c24b@sha256:305c06319216eb636be346047767f04abc406fc2431734a89e63899c6fd2e368 # use pre-built to bootstrap
          name: app-inference
